import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Default port per catalog app name.
 * Port used for the Traefik service loadbalancer server.
 */
export const APP_PORT_MAP: Record<string, number> = {
  authentik:       9000,
  nextcloud:         80,
  'it-tools':        80,
  'paperless-ngx':   80,
  vaultwarden:       80,
  bookstack:         80,
  joplin:          22300,
  libretranslate:  5000,
  ollama:          11434,
  openwebui:        8080,
  searxng:          8080,
  'snipe-it':        80,
  'wiki-js':         3000
};

const BASE_DOMAIN = 'irongeeks.eu';

export interface TraefikConfigOptions {
  /** Tenant slug (used in subdomain: <app>.<tenantSlug>.<BASE_DOMAIN>) */
  tenantSlug: string;
  /** VLAN ID — determines backend IP: 10.<vlanId>.10.100 */
  vlanId: number;
  /** Catalog app names to include */
  appNames: string[];
  /** Optional domain override (replaces <app>.<tenantSlug>.<BASE_DOMAIN>) */
  customDomain?: string;
}

/**
 * Renders a Traefik dynamic configuration YAML for a given tenant.
 * Uses HTTP routers with TLS (certResolver: letsencrypt) and per-app backend services.
 */
export function renderTraefikConfig(options: TraefikConfigOptions): string {
  const { tenantSlug, vlanId, appNames, customDomain } = options;
  const backendIp = `10.${vlanId}.10.100`;

  const routers: string[] = [];
  const services: string[] = [];

  for (const app of appNames) {
    const host = customDomain ?? `${app}.${tenantSlug}.${BASE_DOMAIN}`;
    const port = APP_PORT_MAP[app] ?? 80;
    const safeName = `${tenantSlug}-${app}`.replace(/[^a-z0-9-]/g, '-');

    routers.push(
      [
        `    ${safeName}:`,
        `      rule: "Host(\`${host}\`)"`,
        `      entryPoints:`,
        `        - websecure`,
        `      service: ${safeName}`,
        `      tls:`,
        `        certResolver: letsencrypt`
      ].join('\n')
    );

    services.push(
      [
        `    ${safeName}:`,
        `      loadBalancer:`,
        `        servers:`,
        `          - url: "http://${backendIp}:${port}"`
      ].join('\n')
    );
  }

  const lines: string[] = [
    '# Traefik dynamic configuration',
    `# Tenant: ${tenantSlug}  VLAN: ${vlanId}  Backend: ${backendIp}`,
    '# Generated by gmz-cloud-webapp — do not edit manually.',
    '',
    'http:',
    '  routers:',
    routers.join('\n'),
    '',
    '  services:',
    services.join('\n'),
    ''
  ];

  return lines.join('\n');
}

/**
 * Writes the rendered Traefik config YAML to a file.
 * Creates parent directories as needed.
 */
export async function writeTraefikConfig(filePath: string, yaml: string): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, yaml, 'utf8');
}
