---
- name: Ensure unattended-upgrades installed
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    update_cache: true

- name: Disable root SSH login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: restart ssh

- name: Ensure UFW installed
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Enable UFW
  community.general.ufw:
    state: enabled
