services:
  libretranslate:
    image: libretranslate/libretranslate:${LIBRETRANSLATE_VERSION}
    restart: unless-stopped
    environment:
      LT_API_KEYS: "true"
      LT_API_KEYS_DB_PATH: /app/db/api_keys.db
      LT_LOAD_ONLY: ${LIBRETRANSLATE_LANGUAGES}
      LT_THREADS: "4"
      LT_FRONTEND_TIMEOUT: "500"
    volumes:
      - libretranslate_data:/home/libretranslate/.local/share
      - libretranslate_db:/app/db
    labels:
      traefik.enable: "true"
      traefik.http.routers.libretranslate.rule: Host(`${LIBRETRANSLATE_HOST}`)
      traefik.http.routers.libretranslate.entrypoints: websecure
      traefik.http.routers.libretranslate.tls.certresolver: ionos
      traefik.http.services.libretranslate.loadbalancer.server.port: "5000"

volumes:
  libretranslate_data:
  libretranslate_db:
